name: tflux-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - pip
  - spyder-kernels=3.1
  - pip:
      - mlflow
      - dagshub
      - dvc
      - dvc-s3
      - pyglet
      - reportlab
      - codetiming