name: tflux-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - pip
  - pip:
      - mlflow
      - dagshub
      - dvc
      - dvc-s3